import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk0
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk1
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk2
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk3
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk4
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk5
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk6
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk7
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk8
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk9
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk10
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk11
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk12
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk13
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk14
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk15
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk16
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk17
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk18
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk19
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk20
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk21
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk22
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk23
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk24
import InitECandidate.Proofs.BackendStages.TargetChecks.Labels1Chunk25
import InitECandidate.Proofs.BackendStages.TargetChecks.Phase0
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
open Flapjack Flapjack.Compiler.Backend
open InitECandidate.Proofs.BackendStages
namespace InitECandidate.Proofs.BackendStages.TargetChecks
namespace Labels1
def accumulated : Spt (Spt Nat) := (Chunk25.after (Chunk24.after (Chunk23.after (Chunk22.after (Chunk21.after (Chunk20.after (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))))))))))))))
theorem fold_eq : LabToTarget.computeLabelsAlt 0 Phase0.program .ln = accumulated := by
  change LabToTarget.computeLabelsAlt 0 (Chunk0.input ++ (Chunk1.input ++ (Chunk2.input ++ (Chunk3.input ++ (Chunk4.input ++ (Chunk5.input ++ (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))))))))))))))) .ln = accumulated
  rw [Chunk0.labels_append (Chunk1.input ++ (Chunk2.input ++ (Chunk3.input ++ (Chunk4.input ++ (Chunk5.input ++ (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))))))))))))))) (.ln : Spt (Spt Nat))]
  rw [Chunk1.labels_append (Chunk2.input ++ (Chunk3.input ++ (Chunk4.input ++ (Chunk5.input ++ (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))))))))))))) (Chunk0.after (.ln : Spt (Spt Nat)))]
  rw [Chunk2.labels_append (Chunk3.input ++ (Chunk4.input ++ (Chunk5.input ++ (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))))))))))))) (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))]
  rw [Chunk3.labels_append (Chunk4.input ++ (Chunk5.input ++ (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))))))))))) (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))]
  rw [Chunk4.labels_append (Chunk5.input ++ (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))))))))))) (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))]
  rw [Chunk5.labels_append (Chunk6.input ++ (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))))))))) (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))]
  rw [Chunk6.labels_append (Chunk7.input ++ (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))))))))) (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))]
  rw [Chunk7.labels_append (Chunk8.input ++ (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))))))) (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))]
  rw [Chunk8.labels_append (Chunk9.input ++ (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))))))) (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))]
  rw [Chunk9.labels_append (Chunk10.input ++ (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))))) (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))]
  rw [Chunk10.labels_append (Chunk11.input ++ (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))))) (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))]
  rw [Chunk11.labels_append (Chunk12.input ++ (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))))) (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))]
  rw [Chunk12.labels_append (Chunk13.input ++ (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))))) (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))]
  rw [Chunk13.labels_append (Chunk14.input ++ (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))))) (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))]
  rw [Chunk14.labels_append (Chunk15.input ++ (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))))) (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))]
  rw [Chunk15.labels_append (Chunk16.input ++ (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))))) (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))))]
  rw [Chunk16.labels_append (Chunk17.input ++ (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))))) (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))))]
  rw [Chunk17.labels_append (Chunk18.input ++ (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))))) (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))))))]
  rw [Chunk18.labels_append (Chunk19.input ++ (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))))) (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))))))]
  rw [Chunk19.labels_append (Chunk20.input ++ (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))))) (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))))))))]
  rw [Chunk20.labels_append (Chunk21.input ++ (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))))) (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))))))))]
  rw [Chunk21.labels_append (Chunk22.input ++ (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ [])))) (Chunk20.after (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))))))))))]
  rw [Chunk22.labels_append (Chunk23.input ++ (Chunk24.input ++ (Chunk25.input ++ []))) (Chunk21.after (Chunk20.after (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))))))))))]
  rw [Chunk23.labels_append (Chunk24.input ++ (Chunk25.input ++ [])) (Chunk22.after (Chunk21.after (Chunk20.after (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))))))))))))]
  rw [Chunk24.labels_append (Chunk25.input ++ []) (Chunk23.after (Chunk22.after (Chunk21.after (Chunk20.after (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat))))))))))))))))))))))))))]
  rw [Chunk25.labels_append [] (Chunk24.after (Chunk23.after (Chunk22.after (Chunk21.after (Chunk20.after (Chunk19.after (Chunk18.after (Chunk17.after (Chunk16.after (Chunk15.after (Chunk14.after (Chunk13.after (Chunk12.after (Chunk11.after (Chunk10.after (Chunk9.after (Chunk8.after (Chunk7.after (Chunk6.after (Chunk5.after (Chunk4.after (Chunk3.after (Chunk2.after (Chunk1.after (Chunk0.after (.ln : Spt (Spt Nat)))))))))))))))))))))))))))]
  rfl
theorem accumulated_eq : accumulated = Target.labels1 := by
  with_unfolding_all rfl
theorem labels_eq : LabToTarget.computeLabelsAlt 0 Phase0.program .ln = Target.labels1 := fold_eq.trans accumulated_eq
#print axioms labels_eq
end Labels1
end InitECandidate.Proofs.BackendStages.TargetChecks
