import Flapjack.Parser
import Guest.IncludeStr

/-!
The guest as text, and its parse.

`Guest/guest.pp.pnk` (the `ZISK_ACCEL` build) and `Guest/guest-software.pp.pnk`
(the default build) are the cpp-expanded translation units rooted at
`guest/src/main.pnk`, regenerated by `tools/gen-guest-ast.sh`. Nothing downstream evaluates the parser
at build time except `Guest.AstParse`, which checks it once against the
committed AST in `Guest.Ast`.

Lake only tracks this file's own text, not the files `include_str%` reads, so
the generator stamps the sources' hashes below; a changed source therefore
changes this module and forces its rebuild.
-/

-- guest.pp.pnk sha256: 5599b1d28d12cd24524cfce984f6d10951ce3df833dae3bb898f5840497f4d98
-- guest-software.pp.pnk sha256: 4d2e635b9733140aaf77dab1fa1b42a50f930750d40733b26ea05ede1941534d

namespace Guest

open Flapjack

/-- The cpp-expanded `ZISK_ACCEL` guest source. -/
def guestSource : String := include_str% "guest.pp.pnk"

/-- The accelerated guest parsed with flapjack's Pancake parser, constants
read as 64-bit words. -/
def guestParse : Except (List Parser.ParseError) (List (Decl (BitVec 64))) :=
  Parser.parseTopDecs (BitVec.ofInt 64) guestSource

/-- The parsed declarations; empty only if the source fails to parse, which
`Guest.AstParse.guestParse_eq_ast` rules out. -/
def guestDeclarations : List (Decl (BitVec 64)) :=
  guestParse.toOption.getD []

namespace Software

/-- The cpp-expanded software (default build) guest source. -/
def guestSource : String := include_str% "guest-software.pp.pnk"

def guestParse : Except (List Parser.ParseError) (List (Decl (BitVec 64))) :=
  Parser.parseTopDecs (BitVec.ofInt 64) guestSource

def guestDeclarations : List (Decl (BitVec 64)) :=
  guestParse.toOption.getD []

end Software

end Guest
