import Flapjack.Parser
import Guest.IncludeStr

/-!
The guest as text, and its parse.

`Guest/guest.pp.pnk` is the cpp-expanded translation unit rooted at
`guest/src/main.pnk`, regenerated by `tools/gen-guest-ast.sh`. Nothing downstream evaluates the parser
at build time except `Guest.AstParse`, which checks it once against the
committed AST in `Guest.Ast`.

Lake only tracks this file's own text, not the files `include_str%` reads, so
the generator stamps the sources' hashes below; a changed source therefore
changes this module and forces its rebuild.
-/

-- guest.pp.pnk sha256: d3cec76f0fd072e943f9be62e201b842317a2aa2adcb51bbd0f5cd9dd74d6016

namespace Guest

open Flapjack

/-- The cpp-expanded guest source. -/
def guestSource : String := include_str% "guest.pp.pnk"

/-- The guest parsed with flapjack's Pancake parser, constants
read as 64-bit words. -/
def guestParse : Except (List Parser.ParseError) (List (Decl (BitVec 64))) :=
  Parser.parseTopDecs (BitVec.ofInt 64) guestSource

/-- The parsed declarations; empty only if the source fails to parse, which
`Guest.AstParse.guestParse_eq_ast` rules out. -/
def guestDeclarations : List (Decl (BitVec 64)) :=
  guestParse.toOption.getD []

end Guest
