import Flapjack.Parser
import Guest.IncludeStr

/-!
The guest as text, and its parse.

`Guest/guest.pp.pnk` is the cpp-expanded translation unit rooted at
`guest/src/main.pnk`, regenerated by `tools/gen-guest-ast.sh`. The challenge fixes the committed AST in `Guest.Ast`. Parsing this text and
the AST generation command remain available as tools; the certificate does
not require parser agreement. The AST header records historical provenance.

Lake only tracks this file's own text, not the files `include_str%` reads, so
the generator stamps the sources' hashes below; a changed source therefore
changes this module and forces its rebuild.
-/

-- guest.pp.pnk sha256: d3cec76f0fd072e943f9be62e201b842317a2aa2adcb51bbd0f5cd9dd74d6016

namespace Guest

open Flapjack

/-- The cpp-expanded guest source. -/
def guestSource : String := include_str% "guest.pp.pnk"

/-- The guest parsed with flapjack's Pancake parser, constants
read as 64-bit words. -/
def guestParse : Except (List Parser.ParseError) (List (Decl (BitVec 64))) :=
  Parser.parseTopDecs (BitVec.ofInt 64) guestSource

/-- Optional text-parsed declarations; empty if parsing fails. The challenge
uses `guestAst` directly rather than this fallback. -/
def guestDeclarations : List (Decl (BitVec 64)) :=
  guestParse.toOption.getD []

end Guest
